export const SCRAPER_CONFIG = {
    categories: [
        "Restoran", "Kafe", "Dönerci", "Kebapçı", "Balık Restoran", "Tatlıcı",
        "Pastane", "Fırın", "Ekmek Fırını", "Burger", "Pizza", "Meyhane",
        "Kahvaltıc", "Çorbacı", "Pideci", "Lahmacuncu", "Çiğ Köfteci",
        "Kokoreççi", "Tantuni", "Sushici", "Steakhouse", "Ocakbaşı",
        "Çay Bahçesi", "Pub", "Bar", "Gece Kulübü", "Lokanta", "Börekçi",
        "Waffle", "Kumpir", "Mantı", "Pilavcı", "Dondurma", "Sandviç",
        "Tost", "Gözleme", "Nargile Kafe", "Kahve", "Çay Evi",
        "Hastane", "Özel Klinik", "Eczane", "Diş Kliniği", "Diş Hastanesi",
        "Estetik Merkezi", "Plastik Cerrahi", "Diyetisyen", "Veteriner",
        "Psikolog", "Psikiyatri", "Fizyoterapi", "Optik", "İşitme Cihazları",
        "Medikal", "Laboratuvar", "Poliklinik", "Sağlık Kabini", "Diyaliz Merkezi",
        "Onkoloji", "Çocuk Kliniği", "Kadın Doğum", "Ortopedi", "Dermatoloji",
        "Berber", "Kuaför", "Erkek Kuaförü", "Güzellik Salonu", "Lazer Epilasyon",
        "Masaj Salonu", "SPA", "Hamam", "Solaryum", "Dövmeci", "Piercing",
        "Tırnak Stüdyosu", "Cilt Bakım", "Protez Tırnak", "Kalıcı Makyaj",
        "Tesisatçı", "Elektrikçi", "Oto Tamir", "Oto Yıkama", "Oto Lastik",
        "Oto Elektrik", "Oto Ekspertiz", "Oto Galeri", "Oto Kiralama",
        "Çilingir", "Kuru Temizleme", "Terzi", "Ayakkabı Tamiri", "Anahtarcı",
        "Halı Yıkama", "Beyaz Eşya Servisi", "Kombi Servisi", "Telefon Tamiri",
        "Bilgisayar Tamiri", "Klima Servisi", "Cam Balkon",
        "Market", "Tekel", "Şarküteri", "Manav", "Kasap", "Balıkçı",
        "Kuruyemiş", "Baharatçı", "Çiçekçi", "Kuyumcu", "Saatçi",
        "Giyim Mağazası", "Ayakkabıcı", "Çanta", "Kırtasiye", "Oyuncakçı",
        "Pet Shop", "Züccaciye", "Tuhafiye", "Aktar", "Kitabevi",
        "Elektronik Mağazası", "Spor Malzemeleri", "Bebe Mağazası",
        "Emlakçı", "Nakliyat", "Mobilyacı", "Perdeci", "İnşaat Malzemeleri",
        "Hırdavat", "Boya Badana", "Dekorasyon", "Parke Zemin", "Mutfak Banyo",
        "Spor Salonu", "Fitness", "Pilates", "Yoga", "Halı Saha",
        "Yüzme Havuzu", "Boks Spor Salonu", "Jimnastik", "Dövüş Sporu",
        "Düğün Salonu", "Organizasyon", "Fotoğrafçı", "Matbaa",
        "Reklam Ajansı", "Yazılım Şirketi", "Muhasebe", "Avukat", "Mali Müşavir",
        "Sigorta Acentesi", "Sürücü Kursu", "Dil Kursu", "Kreş", "Anaokulu",
        "Otel", "Pansiyon", "Apart", "Kargo", "Noter",
        "Benzin İstasyonu", "Otopark", "Kuryecilik", "Temizlik Şirketi"
    ],
    districts: [
        "Ataşehir", "Kadıköy", "Maltepe", "Kartal", "Pendik", "Tuzla",
        "Ümraniye", "Üsküdar", "Beykoz", "Sancaktepe", "Sultanbeyli",
        "Çekmeköy", "Şile",
        "Beşiktaş", "Beyoğlu", "Şişli", "Kağıthane", "Eyüpsultan", "Fatih",
        "Gaziosmanpaşa", "Bayrampaşa", "Esenler", "Güngören", "Bahçelievler",
        "Bağcılar", "Bakırköy", "Zeytinburnu", "Küçükçekmece",
        "Beylikdüzü", "Avcılar", "Esenyurt", "Büyükçekmece", "Başakşehir",
        "Arnavutköy", "Sultangazi", "Sarıyer", "Çatalca", "Silivri", "Adalar"
    ],
    city: "İstanbul"
}
